# -*- coding: utf-8 -*-
"""Vdd_lab1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E7M7KJ7kj7buQPcpvOgtkQGqM_Y7jUU4

# **[LAB1.2] 2ª Entrega do Lab1 - Visualização de Dados (TECC)**

## **ENUNCIADO**

Esta atividade prática em grupo consiste na implementação de um projeto de visualização de dados de forma programática, em laboratório de informática. 

Para o ferramental, vamos precisar apenas do Google Colab e das bibliotecas Python: Pandas e GeoPandas. Comece iniciando um novo Notebook Colab a partir do Google Drive de um membro do grupo. Uma vez criado/iniciado, é possível compartilhar o notebook com os demais membros do grupo.

## Preparando Setup

Lendo dados e importando bibliotecas necessárias para a análise.
"""

!pip install geopandas

import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

geo_data = gpd.read_file('/content/drive/MyDrive/vdd/uf.json')
parlamentares = pd.read_csv('/content/drive/MyDrive/vdd/cota-parlamentar.csv')

parlamentares.head()

geo_data.head()

"""## Tratamento dos dados relativos aos parlamentares

Alterações feitas no dataset:
  * Separando colunas uteis para a análise.
  * Filtrando dados pelo ano .
  * Dropando dados faltantes.

"""

parlamentares_ = parlamentares[['vlrliquido', 'nudeputadoid', 'sguf', 'numano']]
parlamentares_ = parlamentares_[parlamentares_['numano']== 2019]
parlamentares_.dropna(inplace = True)
parlamentares_.head()

"""## Calculando gastos médios para cada UF

Ações feitas:
  * Contagem de parlamentares por UF.
  * Cálculo da soma total da coluna "vlrliquido" (Coluna que reporesenta ovalor liquido gasto).
  * Calculo do gasto médio por UF.
"""

parl_p_uf = {}
for sguf in parlamentares_['sguf'].unique():
  sguf_df = parlamentares_[parlamentares_['sguf'] == sguf]
  parl_p_uf[sguf] = len(sguf_df['nudeputadoid'].unique())

parl_p_uf

def get_n_parlamentares(sguf):
  parl_p_uf = {'AC': 14,'AL': 14,'AM': 14,'AP': 14,'BA': 55,'CE': 35,'DF': 14,'ES': 16,
              'GO': 27,'MA': 32,'MG': 81,'MS': 16,'MT': 15,'PA': 26,'PB': 18,'PE': 37,
              'PI': 15,'PR': 45,'RJ': 80,'RN': 12,'RO': 13,'RR': 12,'RS': 46,'SC': 27,
              'SE': 12,'SP': 102,'TO': 12}
  return parl_p_uf[sguf]

parlamentares_media = parlamentares_.groupby('sguf').sum()
parlamentares_media['id'] = parlamentares_media.index
parlamentares_media['nparlamentares'] = parlamentares_media['id'].apply(get_n_parlamentares)
parlamentares_media['vlrliquido_medio'] = parlamentares_media['vlrliquido'] / parlamentares_media['nparlamentares']
parlamentares_media.head()

"""## Cruzando dados"""

final_set = pd.merge(parlamentares_media,geo_data, how='inner', on='id')
final_set.drop(['vlrliquido','nparlamentares','name','uf','codigo','regiao'],axis = 1,inplace = True)
final_set.head()

geo_data['vlrliquido_medio'] = final_set['vlrliquido_medio']

"""## Plotando Gráfico"""

fig, ax = plt.subplots(1, figsize=(16,12))
ax.axis('off')
geo_data.plot(column='vlrliquido_medio', 
              cmap='YlOrBr', linewidth=.5, 
              ax=ax, edgecolor='k', legend = True, 
              legend_kwds={'label': "Média em Reais",'orientation': "horizontal"})
plt.title("Média de gastos por parlamentar no ano de 2019, de acordo com seus estados de origem.",fontsize = 15)